name: Lambda Build & Deploy to Dev

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ECR_REPO: ${{ vars.ECR_REPO }}
  
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read 
jobs:
          
  deploy_dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
    env:
      ENV_NAME: ${{ vars.ENV }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}
          
      - name: Deploy to DEV AWS Lambda
        env:
          AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
          LAMBDA_FUNCTION_NAME: ${{ vars.LAMBDA_FUNCTION_NAME }}
        run: |
          echo "Preparing Lambda environment variables for dev"
          CONFIG_FILE="config.$ENV_NAME.properties"
          JSON_OUTPUT_FILE="${CONFIG_FILE%.properties}.json"
          echo "Setting execute permissions for generate_env_json.sh"
          chmod +x .github/workflows/generate_env_json.sh
          echo "Verifying permissions after chmod:"
          ls -l .github/workflows/generate_env_json.sh
          echo "Running generate_env_json.sh"
          ./.github/workflows/generate_env_json.sh "$CONFIG_FILE" "LAMBDA_FUNCTION_NAME=$LAMBDA_FUNCTION_NAME" "PASSWORD=${{ secrets.PASSWORD }}" 
          aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --image-uri $ECR_REPO/$LAMBDA_FUNCTION_NAME:latest --publish
