name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build AWS Lambda Image
        env:
          LAMBDA_FUNCTION_NAME: ${{ secrets.LAMBDA_FUNCTION_NAME }}
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
        run: |
          echo "Building and Packaging for Build: $GITHUB_RUN_NUMBER"
          docker build -t $LAMBDA_FUNCTION_NAME:$GITHUB_RUN_NUMBER -t $LAMBDA_FUNCTION_NAME .

      - name: Push to Amazon ECR
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          LAMBDA_FUNCTION_NAME: ${{ secrets.LAMBDA_FUNCTION_NAME }}
          GITHUB_RUN_NUMBER: ${{ github.run_number }}
        run: |
          docker tag $LAMBDA_FUNCTION_NAME:$GITHUB_RUN_NUMBER ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/$LAMBDA_FUNCTION_NAME:$GITHUB_RUN_NUMBER
          docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/$LAMBDA_FUNCTION_NAME:$GITHUB_RUN_NUMBER

  deploy_dev:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy to DEV AWS Lambda
        env:
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          AWS_OIDC_ROLE_ARN: ${{ secrets.AWS_OIDC_ROLE_ARN }}
          LAMBDA_FUNCTION_NAME: ${{ secrets.LAMBDA_FUNCTION_NAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: |
          sudo yum update -y && sudo yum install -y jq
          echo "Preparing Lambda environment variables for dev"
          CONFIG_FILE="config.dev.properties"
          JSON_OUTPUT_FILE="${CONFIG_FILE%.properties}.json"
          chmod +x generate_env_json.sh
          ./generate_env_json.sh "$CONFIG_FILE" "LAMBDA_FUNCTION_NAME=$LAMBDA_FUNCTION_NAME" "PASSWORD=$ENTEGRATE_PASSWORD"
          aws lambda update-function-configuration --function-name $LAMBDA_FUNCTION_NAME --cli-input-json file://$JSON_OUTPUT_FILE
          aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --image-uri ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_DEFAULT_REGION }}.amazonaws.com/$LAMBDA_FUNCTION_NAME:latest --publish
