name: Lambda Build & Deploy to Dev

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  ECR_REPO: ${{ vars.ECR_REPO }}
  
permissions:
      id-token: write   # This is required for requesting the JWT
      contents: read 
jobs:
          
  deploy_dev:
    runs-on: ubuntu-latest
    environment:
      name: dev
    env:
      ENV_NAME: ${{ vars.ENV }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ vars.AWS_ROLE_ARN }}
          aws-region: ${{ vars.AWS_DEFAULT_REGION }}
          
      - name: Deploy to AWS Lambda
        env:
          AWS_DEFAULT_REGION: ${{ vars.AWS_DEFAULT_REGION }}
          LAMBDA_FUNCTION_NAME: ${{ vars.LAMBDA_FUNCTION_NAME }}
        run: |
          echo "Preparing Lambda environment variables for $ENV_NAME"
          CONFIG_FILE="config.$ENV_NAME.properties"
          JSON_OUTPUT_FILE="${CONFIG_FILE%.properties}.json"
          
          chmod +x .github/workflows/generate_env_json.sh
          ./.github/workflows/generate_env_json.sh "$CONFIG_FILE" "LAMBDA_FUNCTION_NAME=$LAMBDA_FUNCTION_NAME" "PASSWORD=${{ secrets.PASSWORD }}"
          
          echo "Updating Lambda environment variables"
          echo "JSON_OUTPUT_FILE is set to: $JSON_OUTPUT_FILE"
          aws lambda update-function-configuration --function-name $LAMBDA_FUNCTION_NAME --environment file://$JSON_OUTPUT_FILE
          
          sleep 30  

          echo "Updating Lambda function code"
          for i in {1..5}; do
            aws lambda update-function-code --function-name $LAMBDA_FUNCTION_NAME --image-uri $ECR_REPO/$LAMBDA_FUNCTION_NAME:latest --publish && break || echo "Retrying in 10 seconds..." && sleep 10
          done
